# Generated by Django 6.0.1 on 2026-02-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='additional_details',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
