# Generated by Django 6.0.1 on 2026-02-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_additional_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producthighlight',
            name='group',
            field=models.CharField(choices=[('Product Highlights', 'Product Highlights'), ('Additional Details', 'Additional Details')], default='Product Highlights', max_length=50),
        ),
    ]
