# Generated by Django 6.0.1 on 2026-02-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_producthighlight_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_highlights',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
