# Generated by Django 6.0.1 on 2026-02-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_product_highlights'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dial_shape',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
