# Generated by Django 6.0.1 on 2026-02-18 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_dial_shape_product_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='combo_of',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
