# Generated by Django 6.0.1 on 2026-02-18 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_combo_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery_check_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ProductPincode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.CharField(max_length=6)),
                ('is_serviceable', models.BooleanField(default=True)),
                ('delivery_days', models.PositiveIntegerField(default=3)),
                ('dispatch_days', models.PositiveIntegerField(default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pincode_rules', to='product.product')),
            ],
            options={
                'indexes': [models.Index(fields=['product', 'pincode'], name='product_pro_product_b413ba_idx')],
                'unique_together': {('product', 'pincode')},
            },
        ),
    ]
