# Generated by Django 6.0.1 on 2026-02-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_delivery_check_enabled_productpincode'),
    ]

    operations = [
        migrations.CreateModel(
            name='PincodeLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.CharField(max_length=6, unique=True)),
                ('area_name', models.CharField(max_length=100)),
            ],
        ),
    ]
