# Generated by Django 6.0.1 on 2026-02-18 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_pincodelocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpincode',
            name='area_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
