# Generated by Django 6.0.1 on 2026-02-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_product_discount_percent_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='child_category',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='main_category',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
