# Generated by Django 6.0.1 on 2026-02-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_product_discount_percent_alter_product_mrp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seller_name',
            field=models.CharField(default='Meesho Seller', max_length=100),
        ),
    ]
